// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtQXvLSP39DnVNXTBB1YP4QG4AO41-WEo',
    appId: '1:851915303636:web:fc5a2af0ab582d8bf56941',
    messagingSenderId: '851915303636',
    projectId: 'sacred-portal-354808',
    authDomain: 'sacred-portal-354808.firebaseapp.com',
    storageBucket: 'sacred-portal-354808.appspot.com',
    measurementId: 'G-RQ3GMY6PL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjcnss0RdU9u51_SdIq75J35DT9daksjc',
    appId: '1:851915303636:android:8e022e0b2c5b3e94f56941',
    messagingSenderId: '851915303636',
    projectId: 'sacred-portal-354808',
    storageBucket: 'sacred-portal-354808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMWrXVHEtjN28431EmS_XtGf2pRdpUBc',
    appId: '1:851915303636:ios:4e3ccf1f2db3f1c7f56941',
    messagingSenderId: '851915303636',
    projectId: 'sacred-portal-354808',
    storageBucket: 'sacred-portal-354808.appspot.com',
    iosBundleId: 'com.example.diceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQMWrXVHEtjN28431EmS_XtGf2pRdpUBc',
    appId: '1:851915303636:ios:f0a1bfb4ee61d000f56941',
    messagingSenderId: '851915303636',
    projectId: 'sacred-portal-354808',
    storageBucket: 'sacred-portal-354808.appspot.com',
    iosBundleId: 'com.example.diceApp.RunnerTests',
  );
}
